---
# tasks file for net_operations
- name: "Include dut playbook"
  include_tasks: dut.yml
  when: (device_role is defined and device_role == 'dut') or
        (static_analysis_check is defined and static_analysis_check)

- name: "configure sink device before starting traffic"
  include_tasks: config_sink.yml
  when: (device_role is defined and device_role == 'sink') and
        (stage is defined and stage == 'pre_config') and 
        (static_analysis_check is not defined)

- name: "Include traffic source device playbook"
  include_tasks: source.yml
  when: (device_role is defined and device_role == 'source') and
        (static_analysis_check is not defined)

- name: "Include traffic sink device playbook"
  include_tasks: sink.yml
  when: (device_role is defined and device_role == 'sink') and
        (stage is defined and stage == 'post_traffic') and 
        (static_analysis_check is not defined)

- name: "Analyze results"
  include_tasks: analyze.yml
  when: (device_role is defined and device_role == 'analyzer') and
        (static_analysis_check is not defined)
